# Gather and Scatter Operations
Those operations are used to read values on a tensor based on some index, the advantage of these operations are because they are fast.
![Input Output](docs/imgs/gather_illustrated.png "Title")

#### References
* [Pytorch Basic Operations](https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/)
* [Stack Overflow Gather](https://stackoverflow.com/questions/50999977/what-does-the-gather-function-do-in-pytorch-in-layman-terms)
* [Scatter](https://pytorch.org/docs/stable/tensors.html?highlight=scatter#torch.Tensor.scatter)
* [Gather](https://pytorch.org/docs/stable/torch.html#torch.gather)
* [What does scatter do in layman terms](https://discuss.pytorch.org/t/what-does-the-scatter-function-do-in-layman-terms/28037/4)
* [Using Scatter to Convert to One-Hot](https://discuss.pytorch.org/t/convert-int-into-one-hot-format/507/4)

In [1]:
import torch

In [2]:
v = torch.arange(9) + 1
y = v
v = v.view(3, 3)
print(v)
print('Shape:', v.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])


In [3]:
r = torch.gather(v, 1, torch.LongTensor([[0,1],[1,2],[2,0]]))
print(r)
print(r.shape)

tensor([[1, 2],
        [5, 6],
        [9, 7]])
torch.Size([3, 2])


In [4]:
r = torch.gather(v, 1, torch.LongTensor([[0,1],[1,0],[2,1]]))
print(r)
print(r.shape)

tensor([[1, 2],
        [5, 4],
        [9, 8]])
torch.Size([3, 2])


### Scatter
The scatter says “send the elements of x to the following indices in y, according to ROW-WISE (dim 0)”. In layman’s terms, this is saying, for each element in the original
[ 0.3992, 0.2908, 0.9044, 0.4850, 0.6004], [ 0.5735, 0.9006, 0.6797, 0.4152, 0.1732] tensor, we specify a row index (0,1 or 2) to send it to in the tensor we are scattering into.



In [15]:
x = torch.arange(10).view(2,5)
print(x)
y = torch.zeros(3, 5).long()
# index need to have same shape as x
index = torch.tensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]])
# dim, index, source
y.scatter_(0, index, x)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([[0, 6, 7, 3, 4],
        [0, 1, 0, 8, 0],
        [5, 0, 2, 0, 9]])

#### Using Scatter to Convert to One-Hot

In [6]:
batch_size = 3
nb_digits = 4
# Dummy input that HAS to be 2D for the scatter (you can use view(-1,1) if needed)
x = torch.LongTensor(batch_size,1).random_() % nb_digits
print('x')
print(x)
# One hot encoding buffer that you create out of the loop and just keep reusing
y_onehot = torch.FloatTensor(batch_size, nb_digits)

# In your for loop
y_onehot.zero_()
print('y_one_hot')
# The scatter says “send the elements of x to the following indices in torch.zeros, according to ROW-WISE (dim 0)”
y_onehot.scatter_(1, x, 1)

x
tensor([[2],
        [3],
        [0]])
y_one_hot


tensor([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]])